const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //user
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //----------------------------------------------------------------
    //site 
    //city
    //[get_city]
    FETCH_CITIES_SUCCESS: 'FETCH_CITIES_SUCCESS',
    FETCH_CITIES_FAIL: 'FETCH_CITIES_FAIL',
    //create_city
    CREATE_CITY_START: 'CREATE_CITY_START',
    CREATE_CITY_SUCCESS: 'CREATE_CITY_SUCCESS',
    CREATE_CITY_FAIL: 'CREATE_CITY_FAIL',
    //EDIT_city
    EDIT_CITY_START: 'EDIT_CITY_START',
    EDIT_CITY_SUCCESS: 'EDIT_CITY_SUCCESS',
    EDIT_CITY_FAIL: 'EDIT_CITY_FAIL',
    //DELETE_city
    DELETE_CITY_START: 'DELETE_CITY_START',
    DELETE_CITY_SUCCESS: 'DELETE_CITY_SUCCESS',
    DELETE_CITY_FAIL: 'DELETE_CITY_FAIL',
    //[find_city_position]
    FIND_POSITION_CITIES_SUCCESS: 'FIND_POSITION_CITIES_SUCCESS',
    FIND_POSITION_CITIES_FAIL: 'FIND_POSITION_CITIES_FAIL',
    //categories
    //[get_category]
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAIL: 'FETCH_CATEGORIES_FAIL',
    //create_category
    CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAIL: 'CREATE_CATEGORY_FAIL',
    //EDIT_category
    EDIT_CATEGORY_START: 'EDIT_CATEGORY_START',
    EDIT_CATEGORY_SUCCESS: 'EDIT_CATEGORY_SUCCESS',
    EDIT_CATEGORY_FAIL: 'EDIT_CATEGORY_FAIL',
    //DELETE_category
    DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAIL: 'DELETE_CATEGORY_FAIL',

    //----------------------------------------------------------------
    //hotel 
    //[get_hotel]
    FETCH_HOTELS_SUCCESS: 'FETCH_HOTELS_SUCCESS',
    FETCH_HOTELS_FAIL: 'FETCH_HOTELS_FAIL',
    //create_hotel
    CREATE_HOTEL_START: 'CREATE_HOTEL_START',
    CREATE_HOTEL_SUCCESS: 'CREATE_HOTEL_SUCCESS',
    CREATE_HOTEL_FAIL: 'CREATE_HOTEL_FAIL',
    //EDIT_hotel
    EDIT_HOTEL_START: 'EDIT_HOTEL_START',
    EDIT_HOTEL_SUCCESS: 'EDIT_HOTEL_SUCCESS',
    EDIT_HOTEL_FAIL: 'EDIT_HOTEL_FAIL',
    //DELETE_hotel
    DELETE_HOTEL_START: 'DELETE_HOTEL_START',
    DELETE_HOTEL_SUCCESS: 'DELETE_HOTEL_SUCCESS',
    DELETE_HOTEL_FAIL: 'DELETE_HOTEL_FAIL',
    //[GET_HOTEL_BY_CITY]
    FIND_HOTEL_CITIES_SUCCESS: 'FIND_HOTEL_CITIES_SUCCESS',
    FIND_HOTEL_CITIES_FAIL: 'FIND_HOTEL_CITIES_FAIL',
    //[GET_HOTEL_BY_CATEGORY]
    FIND_HOTEL_CATEGORY_SUCCESS: 'FIND_HOTEL_CATEGORY_SUCCESS',
    FIND_HOTEL_CATEGORY_FAIL: 'FIND_HOTEL_CATEGORY_FAIL',
    //[GET_HOTEL_BY_COMPANY]
    FIND_HOTEL_COMPANY_SUCCESS: 'FIND_HOTEL_COMPANY_SUCCESS',
    FIND_HOTEL_COMPANY_FAIL: 'FIND_HOTEL_COMPANY_FAIL',
    //create_guest
    CREATE_GUEST_START: 'CREATE_GUEST_START',
    CREATE_GUEST_SUCCESS: 'CREATE_GUEST_SUCCESS',
    CREATE_GUEST_FAIL: 'CREATE_GUEST_FAIL',
    //[get_guest]
    FETCH_GUESTS_SUCCESS: 'FETCH_GUESTS_SUCCESS',
    FETCH_GUESTS_FAIL: 'FETCH_GUESTS_FAIL',
    //create_company
    CREATE_COMPANY_START: 'CREATE_COMPANY_START',
    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_FAIL: 'CREATE_COMPANY_FAIL',
    //[get_company]
    FETCH_COMPANIES_SUCCESS: 'FETCH_COMPANIES_SUCCESS',
    FETCH_COMPANIES_FAIL: 'FETCH_COMPANIES_FAIL',
    //[get roomtype]
    FETCH_ROOMTYPE_SUCCESS: 'FETCH_ROOMTYPE_SUCCESS',
    FETCH_ROOMTYPE_FAIL: 'FETCH_ROOMTYPE_FAIL',

    //[get room]
    FETCH_ROOM_SUCCESS: 'FETCH_ROOM_SUCCESS',
    FETCH_ROOM_FAIL: 'FETCH_ROOM_FAIL',


    CREATE_BOOKING_START: 'CREATE_BOOKING_START',
    CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
    CREATE_BOOKING_FAIL: 'CREATE_BOOKING_FAIL',
})

export default actionTypes;